---
- hosts: all
  tasks:
  - name: Install required packages
    apt: name={{ item }} update_cache=yes state=present
    with_items:
      - build-essential
      - git-core
      - curl
      - sqlite3
      - libsqlite3-dev
      - libxml2-dev
      - libxslt1-dev
      - libreadline-dev
      - libyaml-dev
      - libcurl4-openssl-dev
      - libncurses5-dev
      - libgdbm-dev
      - libffi-dev
      - runit
      - postgresql-9.3
      - libpq-dev
      - nodejs
  - name: Create user
    user:
      name: sinatraUser
      createhome: yes
      shell: /bin/bash
      group: root
      generate_ssh_key: yes
  - name: Copy SSH Key
    authorized_key:
      key: "{{ lookup('file', '/Users/nirajkhanal/.ssh/id_rsa.pub') }}"
      user: "sinatraUser"
      state: present
  - name: Download Ruby Build
    git:
      repo: https://github.com/sstephenson/ruby-build.git
      dest: /home/sinatraUser/ruby-build
      accept_hostkey: yes
  - name: Install Ruby-Build
    shell: ./install.sh
    args:
      chdir: /home/sinatraUser/ruby-build
      creates: /usr/local/bin/ruby-build
  - name: Install Ruby
    shell: ruby-build 2.2.2 /home/sinatraUser/local/ruby-2.2.2
    args:
      creates: /home/sinatraUser/local/ruby-2.2.2
  - name: Make sinatraUser owner of ruby folder
    file:
      path: /home/sinatraUser/local/ruby-2.2.2
      state: directory
      group: root
      owner: sinatraUser
      recurse: yes
  - name: Add ruby to path
    lineinfile:
      dest: /home/sinatraUser/.profile
      owner: sinatraUser
      state: present
      line: PATH="$PATH:/home/sinatraUser/local/ruby-2.2.2/bin"
  - name: Install bundler gem
    environment:
      PATH: "{{ ansible_env.PATH }}:/home/sinatraUser/local/ruby-2.2.2/bin"
    sudo_user: sinatraUser
    gem: name={{ item }} state=present
    with_items:  
      - bundler
      - passenger
